version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword      # Change this to a secure password
      MYSQL_DATABASE: mydb                   # Your default database name
      MYSQL_USER: admin                      # A user with access to the DB
      MYSQL_PASSWORD: adminpassword          # The password for the admin user
    ports:
      - "3306:3306"                           # Map MySQL port to localhost
    volumes:
      - mysql-data:/var/lib/mysql            # Persistent storage for MySQL data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"                            # Map phpMyAdmin web interface to localhost
    environment:
      PMA_HOST: mysql                        # Connect phpMyAdmin to the MySQL service
      PMA_USER: admin                        # The admin user defined for MySQL
      PMA_PASSWORD: adminpassword            # The admin password defined for MySQL
    depends_on:
      - mysql

volumes:
  mysql-data:                                 # Volumes to persist MySQL data
